#! /usr/bin/env sh
package="cert-gen"
ROOT=$(pwd)

handle_error() {
  echo ""
  echo "Error: $1"
  echo "Run 'cert-gen $2 --help' for usage."

  clean_up
  exit 1
}

clean_up() {
  cd $ROOT
}

global_help() {
  echo "Shell script for generation certificates and key SSL/TLS"
  echo ""
  echo "Usage:"
  echo "cert-gen [command]"
  echo " "
  echo "Available Commands:"
  echo "  root                    create a root certificate and private key to sign the certificates for your services"
  echo "  service                 create a certificate and a private key for service"
  exit 0
}

root_help() {
  echo "Shell script for generation certificates and key SSL/TLS"
  echo ""
  echo "Usage:"
  echo "cert-gen root"
  echo " "
  echo "Available Commands:"
  echo ""
  echo "Flags:"
  echo "  -h, --help               show brief help"
  echo "  -n, --company-name       company name"
  echo "  -o, --dir-cert           output directory"
  exit 0
}

service_help() {
  echo "Shell script for signing certificates and key SSL/TLS"
  echo ""
  echo "Usage:"
  echo "cert-gen service"
  echo " "
  echo "Available Commands:"
  echo ""
  echo "Flags:"
  echo "  -h, --help               show brief help"
  echo "  -d, --domain             domain. ex: domain.com or sub.domain.com"
  echo "  -ca                      input CA crt"
  echo "  -ca-key                  input CA Key"
  echo "  -o, --dir-cert           output directory"
  exit 0
}

root() {
  if [ -z "$NAME" ]; then
    handle_error "missing company name" "$PROCESS"
  fi

  if [ -z "$OUTPUT" ]; then
    OUTPUT=$ROOT
    echo "[cert-gen] No output. Using default: $OUTPUT"
  else 
    if [[ ! -e $OUTPUT ]]; then
      mkdir -p $OUTPUT
    fi
  fi

  CA_KEY=$NAME-ca.key
  CA_CRT=$NAME-ca.crt
  SUBJECT="/O=$NAME"

  echo "[cert-gen] Name: $NAME"
  echo "[cert-gen] Subject: $SUBJECT"
  echo "[cert-gen] Create a root certificate and private key to sign the certificates for your services"
  openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:4096 -keyout $OUTPUT/$CA_KEY -out $OUTPUT/$CA_CRT -subj "$SUBJECT"

  echo "[cert-gen] Printing root CA certificate"
  openssl x509 -in $CA_CRT -noout -text

  echo ""
  echo ""
  echo "********************************************************************************************"
  echo "************************************ WARNING ***********************************************"
  echo "********************************************************************************************"
  echo "--> Keep $CA_KEY and $CA_CRT secure, but available for generating end entities in the future *"
}

service() {
  if [ -z "$DOMAIN" ]; then
    handle_error "missing domain" "$PROCESS"
  fi

  if [ -z "$DOMAIN" ]; then
    handle_error "missing domain" "$PROCESS"
  fi

  if [ -z "$OUTPUT" ]; then
    OUTPUT=$ROOT
    echo "[cert-gen] No output. Using default: $OUTPUT"
  else 
    if [[ ! -e $OUTPUT ]]; then
      mkdir -p $OUTPUT
    fi
  fi

  if [ -z "$CA" ]; then
    handle_error "missing ca root domain" "$PROCESS"
  fi

  if [ -z "$CA_KEY" ]; then
    handle_error "missing ca key root domain" "$PROCESS"
  fi

  NAME="$(echo $DOMAIN | awk -F "." '{print $1}'), Inc."
  DOMAIN_KEY=$DOMAIN.key
  DOMAIN_CSR=$DOMAIN.csr
  DOMAIN_CRT=$DOMAIN.crt
  SUBJECT="/O=$NAME /CN=$DOMAIN"

  echo "[cert-gen] Service Name: $DOMAIN"
  echo "[cert-gen] Create a certificate and a private key"
  openssl req -nodes -newkey rsa:4096 -keyout $OUTPUT/$DOMAIN_KEY -out $OUTPUT/$DOMAIN_CSR -subj "$SUBJECT"
  echo "[cert-gen] Signing certificate"
  openssl x509 -req -sha256 -days 365 -CA $CA -CAkey $CA_KEY -set_serial 0 -in $OUTPUT/$DOMAIN_CSR -out $OUTPUT/$DOMAIN_CRT
  echo "[cert-gen] Printing signed certificate"
  openssl x509 -in $DOMAIN_CRT -noout -text
  echo ""
  echo ""
  echo "********************************************************************************************"
  echo "************************************ WARNING ***********************************************"
  echo "********************************************************************************************"
  echo "--> Keep these files secure: $DOMAIN_KEY, $DOMAIN_CRT, $DOMAIN_CSR"
}

while test $# -gt 0; do
  case "$1" in
    -h|--help)
      global_help ;;
    root)
      shift
      PROCESS="root"
      while test $# -gt 0; do
        case "$1" in
          -h|--help)
            root_help ;;
          -n|--company-name)
            shift
            if test $# -gt 0; then
              NAME=$1
            else
              echo "[cert-gen] flag -n :: NAME no input name specified."
              exit 1
            fi  
            shift
            ;;
          # -s)
          #   shift
          #   if test $# -gt 0; then
          #     export SECRET=$1
          #   else
          #     echo "[cert-gen] flag -s :: SECRET no input name specified."
          #     exit 1
          #   fi  
          #   shift
          #   ;;
          -o)
            shift
            if test $# -gt 0; then
              OUTPUT=$1
            else
              echo "[cert-gen] no output dir specified"
              exit 1
            fi
            shift
            ;;
          *)
            handle_error "unknown flag \"$1\" for \"cert-gen root\"" "root"
            exit 1
            break
            ;;
        esac
      done
      shift
      ;;
    service)
      shift
      PROCESS="service"
      while test $# -gt 0; do
        case "$1" in
          -h|--help)
            service_help ;;
          -d|--domain)
            shift
            if test $# -gt 0; then
              DOMAIN=$1
            else
              echo "[cert-gen] flag -d :: SERVICE_NAME no input name specified."
              exit 1
            fi  
            shift
            ;;
          -ca)
            shift
            if test $# -gt 0; then
              export CA=$1
            else
              echo "[cert-gen] flag -ca :: CA no input name specified."
              exit 1
            fi 
            shift
            ;;
          -ca-key)
            shift
            if test $# -gt 0; then
              export CA_KEY=$1
            else
              echo "[cert-gen] flag -ca-key :: CA_KEY no input name specified."
              exit 1
            fi
            shift
            ;;
          -o)
            shift
            if test $# -gt 0; then
              export OUTPUT=$1
            else
              echo "[cert-gen] flag -o :: no output dir specified"
              exit 1
            fi
            shift
            ;;
          *)
            handle_error "unknown flag \"$1\" for \"cert-gen root\"" "service"
            exit 1
            break
            ;;
        esac
      done
      shift
      ;;
    *)
      handle_error "unknown flag \"$1\" for \"cert-gen\""
      exit 1
      break
      ;;
  esac
done

# if [ -z "$SECRET" ]; then
#   handle_error "missing secret name"
# fi

if [ $PROCESS == "root" ]; then
  root
fi

if [ $PROCESS == "service" ]; then
  service
fi
