#!/bin/sh
. ~/.config/hyprland/hyprv.conf

#Check the version
VER=$(readlink -f ~/.config/waybar/config.jsonc | cut -d '-' -f1 | cut -d '/' -f8)

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f3)

#if the theme is not dark then we need to switch to it
if [[ $THEMEIS == "" ]]; then
	SWITCHTO="-dark"
	MODESTR="Dark"
else
	MODESTR="Light"
fi

#show a message
notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to $MODESTR"

#set the waybar theme
ln -sf ~/.config/hyprland/waybar/style/$VER'-style'$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/hyprland/wofi/style/$VER'-style'$SWITCHTO.css ~/.config/wofi/style.css

#set the mako theme
ln -sf ~/.config/hyprland/mako/conf/config$SWITCHTO ~/.config/mako/config

#set the measuring unit
ln -sf ~/.config/hyprland/waybar/conf/mesu.jsonc ~/.config/hyprland/waybar/conf/mesu.jsonc

#set the xfce and GTK theme
xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita$SWITCHTO"
xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"

gsettings set org.gnome.desktop.interface icon-theme "Adwaita$SWITCHTO"
gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"

#change the background image and be cool about it ;)
if [ -z $SET_BG ]; then
	swww img ~/.config/hyprland/backgrounds/$VER'-background'$SWITCHTO.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
else
	swww img $SET_BG --transition-fps 60 --transition-type wipe --transition-duration 2
fi

#update the sddm image
cp -f ~/.config/hyprland/backgrounds/$VER'-background'$SWITCHTO.jpg /usr/share/sddm/themes/sdt/wallpaper.jpg

#reset mako
sleep 1
pkill mako
mako &

#restart the waybar
#killall -SIGUSR2 waybar <-- start causing web brwsers to close so switched to below...
pkill waybar
waybar &
